### ISSUE TITLE
after forking checklist

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2024-biologging-class#1]
**gh-pages** --> create a new branch to make these changes. use `git checkout -b ＜new-branch＞`

- [x] - edit the code within each episode to remove the lines that apply to different Nodes
- [x] - edit episode 00 code to remove any packages we will not be discussing
- [x] - remove entire lessons we're not teaching and re-number the episodes accordingly
- [x] - edit index.md to include an accurate summary of the workshop
- [x] - edit config.yml to have accurate title
- [x] - edit README.md
- [x] - remove excess files from Resources folder
- [x] - edit setup.md, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - edit Resources/install_instructions.docx, including link to git repo (two places to change this) and remove extra packages we dont need

**master** --> create a new branch to make these changes. use `git checkout -b ＜new-branch＞`
- [x] - remove excess Data folders
- [x] - remove excess Code folders
- [x] - edit README.md
- [x] - edit setup/setup.R, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - edit setup/install_instructions.docx, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - confirm master is the `default` branch (in Settings tab, along the top). this way participants will not accidently download the .md files, but will download the .R files and dataset

**Comment by CaitlinBate** [comment]
lookin good
